### ISSUE TITLE
Sorting alphabetically?

### ISSUE THREAD

**Issue by karllhughes** [malgamves/CommunityWriterPrograms#10]
Just to show we don't have bias towards one program or another and to make it easier to find existing programs, what do you think about sorting alphabetically?

I'll open up a PR for it if you're interested.

**Comment by malgamves** [comment]
That's a ready good point! When coming up with the list I just threw programs in as I found them. 

Would very much appreciate that PR, thanks!

**Comment by malgamves** [comment]
No that it's sorted I think we should mention that all contributions must follow the format. Might be worth setting up a contributing.md file to explain all this.
