### ISSUE TITLE
LogRocket not accepting new Guest Authors 

### ISSUE THREAD

**Issue by Frank-dev20** [malgamves/CommunityWriterPrograms#120]
[LogRocket ](https://blog.logrocket.com/become-a-logrocket-guest-author/) According to the announcement on their website that read as follows "**We’re not accepting new applicants for our guest author program at the moment. Check back soon**!"

LogRocket has at least for now paused new application.

**Comment by karllhughes** [comment]
@Frank-dev20 thanks for the heads up. Mind submitting a PR? We should remove them from the list until they re-open the applications.

**Comment by Frank-dev20** [comment]
> @Frank-dev20 thanks for the heads up. Mind submitting a PR? We should remove them from the list until they re-open the applications.

Yea. I'll make PR
