### ISSUE TITLE
100ms link doesn't work

### ISSUE THREAD

**Issue by pathbreak** [malgamves/CommunityWriterPrograms#125]
https://www.100ms.live/technical-writer-program shows a 404.
Googling for "technical writer program" on their site doesn't throw up any alternative URLs.

**Comment by karllhughes** [comment]
Thanks for the heads up @pathbreak. Would you be willing to submit a PR removing the program for us?

**Comment by pathbreak** [comment]
@karllhughes Sure! Coming shortly.
