### ISSUE TITLE
404 on the gitlab link

### ISSUE THREAD

**Issue by OlivierJM** [malgamves/CommunityWriterPrograms#14]
The link to the gitlab community writer returns a 404 https://about.gitlab.com/community/writers/ 

It looks like it used to reside [here](https://about.gitlab.com/handbook/marketing/blog/community-writers/) but not anymore. I think it would be good to file an issue to gitlab as well.

Note: The link isn't wrong, It was moved or removed by gitlab

**Comment by malgamves** [comment]
Hey @OlivierJM thanks for the heads up. I did some digging and GitLab retired the program so I will have to take it off the list.

**Comment by OlivierJM** [comment]
ahhhh that makes sense. let me see if I can help with that.

**Comment by malgamves** [comment]
Thanks!
