### ISSUE TITLE
WPhub link is 404

### ISSUE THREAD

**Issue by navjotjsingh** [malgamves/CommunityWriterPrograms#141]
The link is 404. The alternative link is the contact page which doesn't work and has no information about the program.

**Comment by karllhughes** [comment]
@navjotjsingh do you know if they shut down the program officially or just moved the page?

I can't find a new page that has details for writers, so if you don't know of one, we should remove them from this list. Thanks!

**Comment by navjotjsingh** [comment]
I tried reaching them but there seems to be no way. The contact page itself doesn't work. I suggest it should be removed for now.

**Comment by karllhughes** [comment]
@navjotjsingh mind submitting a PR? Thanks!

**Comment by navjotjsingh** [comment]
Done.
