### ISSUE TITLE
codecov link write for us link is broken

### ISSUE THREAD

**Issue by ezesundayeze** [malgamves/CommunityWriterPrograms#145]
[Codecov - Write for us](https://about.codecov.io/write-for-us/)

Noticed they [joined Sentry](https://about.codecov.io/blog/codecov-is-joining-sentry-heres-what-you-need-to-know/) last December. That might have changed things around the writing program, yea?

**Comment by malgamves** [comment]
Oh nice for them, that would explain the program closing. Could you open a PR to take it off the list? If not I can do that a little later this week @ezesundayeze

**Comment by karllhughes** [comment]
Just removed it
