### ISSUE TITLE
DeepSource

### ISSUE THREAD

**Issue by Roy-Wanyoike** [malgamves/CommunityWriterPrograms#167]
[DeepSource](https://www.digitalocean.com/community/pages/write-for-digitalocean)
Pays: Up to $150 Per Article
DeepSource is looking for technical writers who can write content in the form of blogposts and articles on topics related to the following topics: code quality, code review, static analysis, software engineering best practices, etc.

**Comment by Ranny2020** [comment]
I am interested

**Comment by karllhughes** [comment]
@Roy-Wanyoike thanks for submitting all of these programs as issues, but I think maybe you're misunderstanding how to use this repo.

You can find all the writer programs here in this file: https://github.com/malgamves/CommunityWriterPrograms/blob/master/README.md

And if you want to add one that's not already present, you can [submit a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Thanks again, I appreciate you giving back to the community!
