### ISSUE TITLE
adam the automator application on hold

### ISSUE THREAD

**Issue by therealJimoh** [malgamves/CommunityWriterPrograms#173]
Adam the Automator currently not accepting new authors and application on hold

**Comment by malgamves** [comment]
hey @therealJimoh thanks for noticing, could you open a PR that adds that fact that they have halted applications? If not, i'll add something later this week

**Comment by therealJimoh** [comment]
@malgamves Sure. I will do that before EOD 28/03.

**Comment by therealJimoh** [comment]
@malgamves I just raised a PR.

**Comment by karllhughes** [comment]
Removed
