### ISSUE TITLE
Add scam sites that actually don't pay or let's do a rating thing 

### ISSUE THREAD

**Issue by Qodestackr** [malgamves/CommunityWriterPrograms#176]
There are multiple platforms that give terrible experience. Push you to write and end up not paying or even delaying payments. I believe giving a gist of that would help others to make decisions during application. What do you think 🤔?

**Comment by deyyanl** [comment]
Nice suggestion, bumping

**Comment by Qodestackr** [comment]
> Nice suggestion, bumping

Yes, I'm talking of something I've gone through,

**Comment by malgamves** [comment]
That is interesting feedback @Qodestackr - how would you suggest we do that? 
Sorry you had a bad experience with some, do you think something like [this](https://shields.io/category/rating) would work?

**Comment by Qodestackr** [comment]
Sure, like @Saintdavidking we cannot just add a section to only rate the 2 experiences we had. We need a pool of reviews and ratings that those who rely on this platform can always check before deciding to start work on certain products. Especially those who manipulate writers with let's say " 100 dollars + more in credits or reachability" the plus is never triggered no matter what :disappointed:

**Comment by Dule-martins** [comment]
Never had this experience tho but this is sad.

**Comment by Dule-martins** [comment]
> That is interesting feedback @Qodestackr - how would you suggest we do that? Sorry you had a bad experience with some, do you think something like [this](https://shields.io/category/rating) would work?

A space for comments could help as well.

**Comment by Qodestackr** [comment]
> > That is interesting feedback @Qodestackr - how would you suggest we do that? Sorry you had a bad experience with some, do you think something like [this](https://shields.io/category/rating) would work?
> 
> A space for comments could help as well.

😅Gets though coz at times we get into writing with no prior contracts. Companies don't do it as they do with SWE teams. But nonetheless...
