### ISSUE TITLE
CSS Tricks is currently on hold - not accepting new authors

### ISSUE THREAD

**Issue by wisdomekpotu** [malgamves/CommunityWriterPrograms#183]
<img width="1095" alt="Screenshot 2023-04-15 at 7 51 29 PM" src="https://user-images.githubusercontent.com/58194343/232248163-ba1ec959-0570-4cf0-9537-7c716e0da5ba.png">

**Comment by karllhughes** [comment]
@wisdomekpotu thanks for the heads up. I removed them from the list for now.
