### ISSUE TITLE
Most of these Programs are currently not accepting writers

### ISSUE THREAD

**Issue by therevealer** [malgamves/CommunityWriterPrograms#185]

**Comment by xTrilton** [comment]
Yes, the tech industry was hit with massive layoffs and budget cut offs. Most of these tech writing programs were heavily affected.

**Comment by Davisy** [comment]
Wow, this is a bad news!

**Comment by Dule-martins** [comment]
Yeah, it was so bad that it didn't affect the word count but the pay.
