### ISSUE TITLE
Others to add after reasearch

### ISSUE THREAD

**Issue by ChrisChinchilla** [malgamves/CommunityWriterPrograms#19]
- Coralogix
- OverOps
- Ray Wenderlich
- Sqreen
- Envato

**Comment by malgamves** [comment]
These look great!

**Comment by karllhughes** [comment]
Closing as it's been so long. @ChrisChinchilla feel free to make a PR if any of these programs are worth adding to the list. Thanks!

**Comment by ChrisChinchilla** [comment]
Oh sorry, completely forgot but I also have no idea right now about any of these programs…
