### ISSUE TITLE
Add Technical Writing Resources 

### ISSUE THREAD

**Issue by malgamves** [malgamves/CommunityWriterPrograms#30]
Add a section for technical writing resources

**Comment by karllhughes** [comment]
Is there an "awesome list" for technical writing? Or maybe for community writing specifically?

Maybe we could turn this into one?

**Comment by malgamves** [comment]
There is an [Awesome Technical Writing](https://github.com/BolajiAyodeji/awesome-technical-writing) repo. It would be nice to a section for it here and possibly a section for our resource on that repo too.

**Comment by karllhughes** [comment]
I feel like we could put our resources over there in the awesome list and keep this repo focused on writing opportunities. It just doesn't make sense to re-do work since both projects are open source.

Just my 2 cents. Not a big deal either way

**Comment by malgamves** [comment]
Completely agree, I'll make a PR to add our list to theirs. 

Although we can add a quick link mentioning their list. Something like "...you can find resources to help you in your writing journey over at [Awesome Technical Writing]()"

**Comment by karllhughes** [comment]
That's a good idea. I like referencing other specialized resources rather than trying to make ours do everything.

**Comment by malgamves** [comment]
Great! I'll put together a PR for this soon 🗒️ ✍️
