### ISSUE TITLE
Create group for discussion 

### ISSUE THREAD

**Issue by krissnawat** [malgamves/CommunityWriterPrograms#32]
create some Facebook group for discussing anything related to the technical writer program eg. quick update for the new program,how to pitch, pros and cons of the program that we joined, etc.

**Comment by malgamves** [comment]
hey, the Write the Docs community has a Slack that serves this exact purpose - you can [join here](https://www.writethedocs.org/slack/)

**Comment by karllhughes** [comment]
@krissnawat closing for now. While a discussion group is a neat idea, I agree with @malgamves that the Write the Docs community and GitHub issues are probably enough for now.

Happy to re-open if we feel those channels aren't enough.
