### ISSUE TITLE
Section.io's Engineering Education Blog

### ISSUE THREAD

**Issue by karllhughes** [malgamves/CommunityWriterPrograms#33]
Recently stumbled on an article on Section.io's Engineering Education blog and saw that they accept external contributors and pay them: https://github.com/section-io/engineering-education

The only hitch is that you have to be a CS student, and I'm not sure how much they pay. I think it's worth including on our list though, @malgamves what do you think?

**Comment by malgamves** [comment]
Hey @karllhughes , I think that's fine. We can add a note about how anyone submitting should be a student. A few other publications have restrictions too so it would make sense to add this one too
